"""
Julia implementation of the FGBA model by Wuyts and Sieber (2024)
https://doi.org/10.1073/pnas.2211853120

The KMC implementation is based on the Matlab code by Wuyts
(https://github.com/b-wuyts/fgba/blob/main/KMC.m)

Author: Reyk Börner
Parts of this code have been generated by Claude (Sonnet-5).
"""

using Agents, Random
using Base64

Base.@kwdef struct FGBA_parameters
    L::Int = 50
    initial_grass_fraction::Float64 = 1.0
    p_grass::Float64 = 0.9
    p_forest::Float64 = 0.1
    lambda::Float64 = 5.0
    mu::Float64 = 1.0e6
    alpha::Float64 = 0.03
    beta::Float64 = 0.0002
    gamma::Float64 = 0.02
    phi::Float64 = 1e-5
end

@agent struct Automata(GridAgent{2}) end

# Cell states
const F = 1     # F: forest
const G = 2     # G: grass
const B = 3     # B: burning
const A = 4     # A: ash

# Define nearest neighbors on domain (with periodic boundary conditions)
@inline function von_neumann_neighbors(I::CartesianIndex{2}, L::Int)
    i, j = Tuple(I)
    return (
        CartesianIndex(mod1(i - 1, L), j),
        CartesianIndex(mod1(i + 1, L), j),
        CartesianIndex(i, mod1(j - 1, L)),
        CartesianIndex(i, mod1(j + 1, L)),
    )
end

"""
    fgba_model(p::FGBA_parameters; kwargs...)

Initialize the FGBA model using the parameter settings `p`.

## Keyword arguments
- seed=42: random seed
"""
function fgba_model(p::FGBA_parameters; seed=42)
    (; L, initial_grass_fraction, p_grass, p_forest,
        lambda, mu, alpha, beta, gamma, phi) = p
    N = L^2
    #phi = phi === nothing ? 0.1 / N : phi
    rho_grass = mu * p_grass / (1 - p_grass)   # fire contagion rate in grass  (M2(G,B,B))
    rho_forest = mu * p_forest / (1 - p_forest)   # fire contagion rate in forest (M2(F,B,B))

    space = GridSpaceSingle((L, L); periodic = true, metric = :manhattan)
    rng = Random.MersenneTwister(seed)

    properties = (
        state  = fill(G, L, L),          # X[i] as a single Int per cell
        nF     = zeros(Int, L, L),           # # neighbours currently F
        nB     = zeros(Int, L, L),           # # neighbours currently B
        t      = Ref(0.0),                   # continuous KMC clock
        counts = zeros(Int, 4),              # running per-state cell counts, indexed F..A
        gamma  = Ref(gamma), beta = Ref(beta), phi = Ref(phi), mu = Ref(mu),
        lambda = Ref(lambda), alpha = Ref(alpha),
        rho_forest = Ref(rho_forest), rho_grass = Ref(rho_grass),
    )

    fgba = StandardABM(Automata, space; rng, model_step! = kmc_step!,
                        properties, container = Vector)

    # Initial condition: initial grass fraction, the rest forest,
    # randomly distributed across domain
    nG0 = round(Int, initial_grass_fraction * N)
    isgrass = shuffle(abmrng(fgba), vcat(trues(nG0), falses(N - nG0)))
    for (k, I) in enumerate(CartesianIndices(fgba.state))
        fgba.state[I] = isgrass[k] ? G : F
    end

    # initial neighbor tallies
    for I in CartesianIndices(fgba.state)
        nbrs = von_neumann_neighbors(I, L)
        fgba.nF[I] = count(J -> fgba.state[J] == F, nbrs)
        fgba.nB[I] = count(J -> fgba.state[J] == B, nbrs)
    end

    for s in 1:4
        fgba.counts[s] = count(==(s), fgba.state)
    end

    return fgba
end

"""
    kmc_step!(model)

Performs a KMC Gillespie simulation step.
"""
function kmc_step!(model)
    state = model.state
    nF, nB = model.nF, model.nB
    γ, β, φ, μ, λ, α = model.gamma[], model.beta[], model.phi[], model.mu[], model.lambda[], model.alpha[]
    ρf, ρg = model.rho_forest[], model.rho_grass[]

    L = size(state, 1)
    N = L*L
    cidx = CartesianIndices(state)

    rate1 = Vector{Float64}(undef, N); to1 = Vector{Int}(undef, N)
    rate2 = Vector{Float64}(undef, N); to2 = Vector{Int}(undef, N)

    @inbounds for k in 1:N
        I = cidx[k]
        s = state[I]
        if s == F
            rate1[k], to1[k] = γ, G
            rate2[k], to2[k] = ρf * nB[I], B
        elseif s == G
            rate1[k], to1[k] = β + α * nF[I], F
            rate2[k], to2[k] = φ + ρg * nB[I], B
        elseif s == B
            rate1[k], to1[k] = μ, A
            rate2[k], to2[k] = 0.0, 0
        else # A
            rate1[k], to1[k] = β + α * nF[I], F
            rate2[k], to2[k] = λ, G
        end
    end

    Rtot = sum(rate1) + sum(rate2)
    Rtot <= 0 && return model  # the system has frozen (shouldn't normally happen)

    # Gillespie algorithm
    rng = abmrng(model)
    # Gillespie waiting time: dt ~ Exponential(Rtot)
    model.t[] += -log(rand(rng)) / Rtot

    U = rand(rng) * Rtot
    acc = 0.0
    fired, target = 0, 0
    @inbounds for k in 1:N
        acc += rate1[k]
        if U <= acc
            fired, target = k, to1[k]; break
        end
        acc += rate2[k]
        if U <= acc
            fired, target = k, to2[k]; break
        end
    end
    fired == 0 && return model

    I = cidx[fired]
    old = state[I]
    state[I] = target
    model.counts[old] -= 1
    model.counts[target] += 1

    # update the 4 neighbor cells around the cell that fired
    @inbounds for J in von_neumann_neighbors(I, L)
        old == F    && (nF[J] -= 1)
        target == F && (nF[J] += 1)
        old == B    && (nB[J] -= 1)
        target == B && (nB[J] += 1)
    end

    return model
end

p_default = FGBA_parameters()
fgba = fgba_model(p_default)
step!(fgba, (m, s) -> m.t[] >= 2.0)   # advance until 2 simulated time units
fgba.t[]
#count(==(B), fgba.state)        # cells currently on fire

# Data collection
forest_frac(m) = count(==(F), m.state) / length(m.state)
grass_frac(m)  = count(==(G), m.state) / length(m.state)
burn_frac(m)   = count(==(B), m.state) / length(m.state)
ash_frac(m)    = count(==(A), m.state) / length(m.state)
sim_time(m)    = m.t[]
state_map(m)   = copy(m.state)

# Store data
mdata = [sim_time, forest_frac, grass_frac, burn_frac, ash_frac, state_map]

# Colors
clrF = RGBf(34 / 255, 71 / 255, 42 / 255)     # dark green : forest
clrG = RGBf(189 / 255, 208 / 255, 156 / 255)  # pale green : grass
clrB = RGBf(217 / 255, 145 / 255, 22 / 255)   # orange     : burning
clrA = RGBf(178 / 255, 178 / 255, 178 / 255)  # grey       : ash

function play_gif(filename)
    gif_data = base64encode(read(filename))
    display("text/html", """
    <img src="data:image/gif;base64,$gif_data">
    """)
end